version: '3'

services:

  mysql:
    image: "mysql:5.6"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=satellite_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "6606:3306"

  satellite-mysql:
    image: user-catalog
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8089:8089
    command: sh -c "/wait && /user-catalog"
    environment:
      - WAIT_HOSTS=mysql:3306